#!/usr/bin/env bash
# vi: set ft=sh :
###
#
# Runs various scripts to check the quality of code being checked in
#

# Is language X enabled?
if [[ "true" == $(git config --bool hooks.php.enabled) ]]; then
    source $GIT_DIR/hooks/php/pre-commit
fi

####
#
# Various other languages can be setup and ran the same way
#
#source $GIT_HOOK_DIR/ruby/pre-commit
#source $GIT_HOOK_DIR/python/pre-commit
#source $GIT_HOOK_DIR/javascript/pre-commit
#source $GIT_HOOK_DIR/css/pre-commit
#source $GIT_HOOK_DIR/html/pre-commit
#source $GIT_HOOK_DIR/twig/pre-commit
