#!/bin/sh
# vi: set ft=sh :

# Is tool X enabled?
if [ "true" == $(git config --bool hooks.php.composer.enabled) ]; then
    source $GIT_DIR/hooks/php/composer/pre-commit
fi
if [ "true" == $(git config --bool hooks.php.phpcs.enabled) ]; then
    source $GIT_DIR/hooks/php/phpcs/pre-commit
fi
if [ "true" == $(git config --bool hooks.php.phpmd.enabled) ]; then
    source $GIT_DIR/hooks/php/phpmd/pre-commit
fi

# syntax check
if [ "true" == $(git config --bool hooks.php.lint.enabled) ]; then
    if git rev-parse --verify HEAD >/dev/null 2>&1
    then
            against=HEAD
    else
            against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
    fi
    PHP_BIN=$(command -v php)
    FILES=$(git diff --cached --name-only --diff-filter=ACMR $against | grep "\.php")
    for f in $FILES; do
        $PHP_BIN -l $f
        if [ $? != 0 ]; then
            exit $?
        fi
    done
fi
