#!/usr/bin/env bash
# vi: set ft=sh :
####
#
# pre-commit hook to validate composer.json
#
COMPOSER_BIN=$(git config --path hooks.php.composer.bin)
if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
COMPOSER_JSON_FOUND=$(git diff-index --name-status $against -- composer.json | wc -l)
if [[ $COMPOSER_JSON_FOUND > 0 && -e "$(pwd)/composer.json" ]]; then
    if [ -e $(git config --path hooks.php.composer.bin) ]; then
        $COMPOSER_BIN validate
        #if [ $? != 0 ]; then
        #    exit $?
        #fi
    fi
fi
