#!/usr/bin/env bash
# vi: set ft=sh :
####
#
# post-checkout hook to run composer install if composer.lock is modified
#
COMPOSER_BIN=$(git config --path hooks.php.composer.bin)
if [ -e composer.lock ]; then
    CHANGED=$(git diff $1 $2 --stat -- $GIT_DIR/../composer.lock | wc --lines)
    if [[ 0 < $CHANGED ]]; then
        $COMPOSER_BIN install
        if [ $? != 0 ]; then
            exit $?
        fi
    fi
fi
