#!/bin/sh
###
#
# Runs phpmd to check for violations
#
PHPMD_BIN=$(command -v phpmd)
if [ ! $PHPMD_BIN ]; then
    exit 0
fi
if [ ! $(git config --bool hooks.phpmd.enabled) ]; then
    exit 0;
fi
echo "Starting PHP Mess Detector"
if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
FILES=$(git diff --cached --name-only --diff-filter=ACMR $against | grep \.php)
for f in $FILES; do
    $PHPMD_BIN $f $(git config hooks.phpmd.report) $(git config hooks.phpmd.ruleset)
    if [ $? != 0 ]; then
        GIT_HOOK_FOUND_ERRORS=1
    fi
done
echo "PHP Mess Detection Complete"
