#!/bin/sh
###
#
# Runs various scripts to check the quality of code being checked in
#
GIT_HOOK_DIR="$(dirname "$0")"
GIT_HOOK_FOUND_ERRORS=0

# Scripts go here
source $GIT_HOOK_DIR/phpcs
source $GIT_HOOK_DIR/phpmd

# If errors were found, no commit!
if [ $GIT_HOOK_FOUND_ERRORS ]; then
    exit 1
fi
