#!/bin/sh
# vi: set ft=sh :
###
#
# Runs various scripts to check the quality of code being checked in
#

# Scripts go here
source $GIT_DIR/hooks/php/pre-commit
#source $GIT_HOOK_DIR/ruby/pre-commit
#source $GIT_HOOK_DIR/python/pre-commit
#source $GIT_HOOK_DIR/javascript/pre-commit
#source $GIT_HOOK_DIR/css/pre-commit
#source $GIT_HOOK_DIR/html/pre-commit
#source $GIT_HOOK_DIR/twig/pre-commit
