#!/usr/bin/env bash
# @see https://raw.github.com/revans/bash-it/master/themes/colors.theme.bash

if [ $(command -v dircolors) ]; then
    eval "$(dircolors $DOTFILES_ROOT/lib/dircolors/dircolors.ansi-dark)"
fi
